namespace: mhawk
resources:
  - ./namespace.yml
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml

configMapGenerator:
  - name: mhawk-configmap
    envs:
      - .env.config
secretGenerator:
  - name: mhawk-secret
    envs:
      - .env.secret

generatorOptions:
 disableNameSuffixHash: true
