apiVersion: apps/v1
kind: Deployment
metadata:
  name: mhawk-deployment
  namespace: mhawk
  labels:
    app.kubernetes.io/name: mhawk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mhawk
  template:
      metadata:
        labels:
          app: mhawk
      spec:
        containers:
          - name: app
            image: kieranbamforth/mhawk:51
            ports:
              - containerPort: 3000
            env:
              - name: MYSQL_HOST
                valueFrom:
                  secretKeyRef:
                    name: mhawk-db
                    key: MYSQL_HOST
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: mhawk-db
                    key: MYSQL_USER
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mhawk-db
                    key: MYSQL_PASSWORD
              - name: MYSQL_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: mhawk-db
                    key: MYSQL_DATABASE
              - name: MYSQL_PORT
                valueFrom:
                  secretKeyRef:
                    name: mhawk-db
                    key: MYSQL_PORT
              - name: MONZO_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: mhawk-secret
                    key: MONZO_CLIENT_ID
              - name: MONZO_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: mhawk-secret
                    key: MONZO_CLIENT_SECRET
              - name: KIERAN_MONZO
                valueFrom:
                  secretKeyRef:
                    name: mhawk-secret
                    key: KIERAN_MONZO
              - name: MONZO_REDIRECT
                value: "https://mhawk.k8s.istio.kieranbamforth.me/api/v0/auth/monzo/callback"
              - name: NEXTAUTH_URL
                value: "https://mhawk.k8s.istio.kieranbamforth.me"
              - name: DEBUG
                value: mhawk-*
              - name: ES_INDEX
                valueFrom:
                  secretKeyRef:
                    name: mhawk-es
                    key: ES_INDEX
              - name: ES_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: mhawk-es
                    key: ES_USERNAME
              - name: ES_INDEX
                valueFrom:
                  secretKeyRef:
                    name: mhawk-es
                    key: ES_INDEX
              - name: ES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mhawk-es
                    key: ES_PASSWORD
              - name: ES_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: mhawk-es
                    key: ES_ENDPOINT
            resources:
              limits:
                memory: "400Mi"
              requests:
                cpu: 50m
                memory: "300Mi"
            securityContext:
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
